/**
 * 配置表单状态管理 Hook
 * 处理 TOML 解析、表单状态、验证和序列化
 */

import { useState, useCallback, useEffect, useMemo } from 'react'
import { invoke } from '@tauri-apps/api/core'
import type { ConfigData, ConfigFieldSchema, EditorMode, CollapsedState, ConfigValue } from '@/types/config'
import { getAllFields, getFieldDefaults } from '@/schemas/configSchema'

// 简单的 TOML 解析器（不依赖外部库）
function parseToml(content: string): ConfigData {
  const result: ConfigData = {}
  let currentSection = result
  let currentSectionName = ''

  const lines = content.split('\n')
  for (const line of lines) {
    // 跳过空行和注释
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue

    // Section header
    const sectionMatch = trimmed.match(/^\[([^\]]+)\]$/)
    if (sectionMatch) {
      currentSectionName = sectionMatch[1]
      const parts = currentSectionName.split('.')
      currentSection = result
      for (const part of parts) {
        if (!currentSection[part]) {
          currentSection[part] = {}
        }
        currentSection = currentSection[part] as ConfigData
      }
      continue
    }

    // Key-value pair
    const kvMatch = trimmed.match(/^([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(.+)$/)
    if (kvMatch) {
      const key = kvMatch[1]
      let value: any = kvMatch[2].trim()

      // 解析值类型
      if (value.startsWith('"') && value.endsWith('"')) {
        // 字符串
        value = value.slice(1, -1)
      } else if (value.startsWith("'") && value.endsWith("'")) {
        // 字符串（单引号）
        value = value.slice(1, -1)
      } else if (value === 'true') {
        value = true
      } else if (value === 'false') {
        value = false
      } else if (value === 'null' || value === '') {
        value = null
      } else if (value.startsWith('[')) {
        // 数组
        try {
          value = JSON.parse(value.replace(/'/g, '"'))
        } catch {
          value = []
        }
      } else if (!isNaN(Number(value))) {
        value = Number(value)
      }

      currentSection[key] = value
    }
  }

  return result
}

// 简单的 TOML 序列化器
function serializeToml(data: ConfigData): string {
  const lines: string[] = []
  const processedSections = new Set<string>()

  function processSection(obj: ConfigData, prefix: string = '') {
    const directKeys: string[] = []
    const subSections: [string, ConfigData][] = []

    // 分离直接键和子节
    for (const [key, value] of Object.entries(obj)) {
      if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
        subSections.push([key, value as ConfigData])
      } else {
        directKeys.push(key)
      }
    }

    // 输出直接键值对
    if (directKeys.length > 0 && prefix) {
      lines.push(`[${prefix}]`)
      for (const key of directKeys) {
        const value = obj[key]
        lines.push(`${key} = ${formatValue(value)}`)
      }
      lines.push('')
      processedSections.add(prefix)
    }

    // 递归处理子节
    for (const [sectionKey, sectionValue] of subSections) {
      const fullPrefix = prefix ? `${prefix}.${sectionKey}` : sectionKey
      processSection(sectionValue, fullPrefix)
    }
  }

  function formatValue(value: any): string {
    if (value === null || value === undefined) {
      return '""'
    }
    if (typeof value === 'string') {
      // 转义引号
      return `"${value.replace(/"/g, '\\"')}"`
    }
    if (typeof value === 'boolean') {
      return value ? 'true' : 'false'
    }
    if (Array.isArray(value)) {
      if (value.length === 0) return '[]'
      const items = value.map((item) => formatValue(item))
      return `[${items.join(', ')}]`
    }
    if (typeof value === 'number') {
      return String(value)
    }
    return JSON.stringify(value)
  }

  processSection(data)

  // 添加文件头注释
  const header = `# AnyClaw Configuration File
# Generated by Config Form Editor

`
  return header + lines.join('\n')
}

// 验证字段值
function validateField(field: ConfigFieldSchema, value: any): string | null {
  // 必填检查
  if (field.required && (value === null || value === undefined || value === '')) {
    return 'This field is required'
  }

  // 类型检查
  if (value !== null && value !== undefined && value !== '') {
    switch (field.type) {
      case 'number':
        if (isNaN(Number(value))) {
          return 'Must be a valid number'
        }
        if (field.validation) {
          const num = Number(value)
          if (field.validation.min !== undefined && num < field.validation.min) {
            return `Minimum value is ${field.validation.min}`
          }
          if (field.validation.max !== undefined && num > field.validation.max) {
            return `Maximum value is ${field.validation.max}`
          }
        }
        break

      case 'string':
        if (field.validation?.pattern) {
          const regex = new RegExp(field.validation.pattern)
          if (!regex.test(value)) {
            return `Invalid format`
          }
        }
        break

      case 'enum':
        if (field.validation?.enum && !field.validation.enum.includes(value)) {
          return `Must be one of: ${field.validation.enum.join(', ')}`
        }
        break

      case 'array':
        if (!Array.isArray(value)) {
          return 'Must be an array'
        }
        break
    }
  }

  return null
}

export interface UseConfigFormOptions {
  onSaved?: () => void
}

export function useConfigForm(options: UseConfigFormOptions = {}) {
  const { onSaved } = options

  // 状态
  const [isLoading, setIsLoading] = useState(true)
  const [isSaving, setIsSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [configPath, setConfigPath] = useState<string>('')
  const [originalContent, setOriginalContent] = useState<string>('')
  const [editorMode, setEditorMode] = useState<EditorMode>('form')
  const [tomlContent, setTomlContent] = useState<string>('')
  const [collapsedState, setCollapsedState] = useState<CollapsedState>(() => {
    // 从 localStorage 恢复折叠状态
    try {
      const saved = localStorage.getItem('config-collapsed-state')
      return saved ? JSON.parse(saved) : {}
    } catch {
      return {}
    }
  })
  const [values, setValues] = useState<ConfigData>(() => getFieldDefaults())
  const [errors, setErrors] = useState<Record<string, string>>({})
  const [showAdvanced, setShowAdvanced] = useState(false)

  // 所有字段
  const allFields = useMemo(() => getAllFields(), [])

  // 是否有未保存的更改
  const isDirty = useMemo(() => {
    return tomlContent !== originalContent
  }, [tomlContent, originalContent])

  // 加载配置
  const loadConfig = useCallback(async () => {
    setIsLoading(true)
    setError(null)

    try {
      const path = await invoke<string>('get_config_path_string')
      setConfigPath(path)

      const content = await invoke<string>('read_config_file')
      setOriginalContent(content)
      setTomlContent(content)

      // 解析 TOML 到表单数据
      const parsed = parseToml(content)
      setValues({ ...getFieldDefaults(), ...parsed })
    } catch (e) {
      setError(String(e))
    } finally {
      setIsLoading(false)
    }
  }, [])

  // 初始加载
  useEffect(() => {
    loadConfig()
  }, [loadConfig])

  // 保存折叠状态到 localStorage
  useEffect(() => {
    localStorage.setItem('config-collapsed-state', JSON.stringify(collapsedState))
  }, [collapsedState])

  // 同步表单数据到 TOML 内容
  useEffect(() => {
    if (editorMode === 'form') {
      const newToml = serializeToml(values)
      setTomlContent(newToml)
    }
  }, [values, editorMode])

  // 验证 TOML 内容
  const validateToml = useCallback(async (content: string): Promise<string | null> => {
    try {
      await invoke('validate_toml', { content })
      return null
    } catch (e) {
      return String(e)
    }
  }, [])

  // 更新字段值
  const updateValue = useCallback((key: string, value: ConfigValue) => {
    setValues((prev) => {
      const newData = { ...prev }
      const parts = key.split('.')
      let current = newData

      for (let i = 0; i < parts.length - 1; i++) {
        if (!current[parts[i]]) {
          current[parts[i]] = {}
        }
        current = current[parts[i]] as ConfigData
      }

      current[parts[parts.length - 1]] = value
      return newData
    })

    // 验证字段
    const field = allFields.find((f) => f.key === key)
    if (field) {
      const validationError = validateField(field, value)
      setErrors((prev) => {
        const newErrors = { ...prev }
        if (validationError) {
          newErrors[key] = validationError
        } else {
          delete newErrors[key]
        }
        return newErrors
      })
    }
  }, [allFields])

  // 获取字段值
  const getValue = useCallback((key: string): ConfigValue => {
    const parts = key.split('.')
    let current: any = values

    for (const part of parts) {
      if (current === null || current === undefined) return undefined
      current = current[part]
    }

    return current
  }, [values])

  // 获取字段错误
  const getError = useCallback((key: string): string | undefined => {
    return errors[key]
  }, [errors])

  // 切换分组折叠状态
  const toggleGroupCollapse = useCallback((groupId: string) => {
    setCollapsedState((prev) => ({
      ...prev,
      [groupId]: !prev[groupId],
    }))
  }, [])

  // 检查分组是否折叠
  const isGroupCollapsed = useCallback((groupId: string): boolean => {
    return collapsedState[groupId] ?? false
  }, [collapsedState])

  // 切换编辑模式
  const switchMode = useCallback(async (mode: EditorMode) => {
    if (mode === 'form' && editorMode === 'advanced') {
      // 从高级模式切换到表单模式，需要验证 TOML
      const validationError = await validateToml(tomlContent)
      if (validationError) {
        setError(validationError)
        return false
      }

      // 解析新的 TOML 内容
      const parsed = parseToml(tomlContent)
      setValues({ ...getFieldDefaults(), ...parsed })
    }

    setEditorMode(mode)
    setError(null)
    return true
  }, [editorMode, tomlContent, validateToml])

  // 保存配置
  const save = useCallback(async () => {
    // 验证所有字段
    const newErrors: Record<string, string> = {}
    for (const field of allFields) {
      const value = getValue(field.key)
      const validationError = validateField(field, value)
      if (validationError) {
        newErrors[field.key] = validationError
      }
    }

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors)
      setError('Please fix validation errors before saving')
      return false
    }

    // 验证 TOML 格式
    const validationError = await validateToml(tomlContent)
    if (validationError) {
      setError(validationError)
      return false
    }

    setIsSaving(true)
    setError(null)

    try {
      await invoke('write_config_file', { content: tomlContent })
      setOriginalContent(tomlContent)
      onSaved?.()
      return true
    } catch (e) {
      setError(String(e))
      return false
    } finally {
      setIsSaving(false)
    }
  }, [allFields, getValue, tomlContent, validateToml, onSaved])

  // 重置
  const reset = useCallback(() => {
    setTomlContent(originalContent)
    const parsed = parseToml(originalContent)
    setValues({ ...getFieldDefaults(), ...parsed })
    setErrors({})
    setError(null)
  }, [originalContent])

  // 刷新
  const refresh = useCallback(async () => {
    if (isDirty) {
      if (!confirm('Discard unsaved changes?')) {
        return
      }
    }
    await loadConfig()
  }, [isDirty, loadConfig])

  return {
    // 状态
    isLoading,
    isSaving,
    isDirty,
    error,
    configPath,
    editorMode,
    tomlContent,
    values,
    showAdvanced,

    // 操作
    loadConfig,
    save,
    reset,
    refresh,
    switchMode,
    setTomlContent,
    setShowAdvanced,

    // 表单操作
    updateValue,
    getValue,
    getError,

    // 分组操作
    toggleGroupCollapse,
    isGroupCollapsed,
  }
}
